package com.rasyidin.mygithubapp.profile.domain.model

data class User(
    val reposUrl: String? = null,
    val followingUrl: String? = null,
    val twitterUsername: String? = null,
    val bio: String? = null,
    val createdAt: String? = null,
    val username: String? = null,
    val blog: String? = null,
    val subscriptionsUrl: String? = null,
    val updatedAt: String? = null,
    val company: String? = null,
    val id: Int? = null,
    val publicRepos: Int? = null,
    val email: String? = null,
    val organizationsUrl: String? = null,
    val starredUrl: String? = null,
    val followersUrl: String? = null,
    val url: String? = null,
    val receivedEventsUrl: String? = null,
    val followers: Int? = null,
    val avatarUrl: String? = null,
    val following: Int? = null,
    val name: String? = null,
    val location: String? = null,
)
